import type { Card, CardType } from "../types";
import type { CardGenerator } from "./interface";

const nouns = ["Drake", "Archivist", "Golem", "Voyager", "Sentinel", "Oracle"];
const verbs = ["Ignite", "Echo", "Ward", "Shift", "Pulse", "Anchor"];
const tags = ["arcane", "steel", "forest", "ember", "tide", "rift"];

const hashSeed = (seed: string): number => {
  let hash = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
};

const createRng = (seed?: string) => {
  let state = seed ? hashSeed(seed) : Date.now() % 2147483647;
  return () => {
    state = (state * 48271) % 2147483647;
    return state / 2147483647;
  };
};

const pick = <T>(items: T[], rng: () => number): T =>
  items[Math.floor(rng() * items.length)];

const makeId = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const makeStats = (rng: () => number) => ({
  attack: Math.max(0, Math.floor(rng() * 8)),
  health: Math.max(1, Math.floor(rng() * 12) + 1)
});

const makeCard = (rng: () => number): Card => {
  const type = pick<CardType>(["unit", "spell", "artifact", "location"], rng);
  const name = `${pick(verbs, rng)} ${pick(nouns, rng)}`;
  const card: Card = {
    id: makeId(name),
    name,
    type,
    cost: Math.floor(rng() * 8),
    text: "Generated by mock engine.",
    tags: [pick(tags, rng)]
  };
  if (type === "unit") {
    card.stats = makeStats(rng);
  }
  return card;
};

export const createMockGenerator = (): CardGenerator => ({
  name: "mock",
  generate: (seed?: string) => {
    const rng = createRng(seed);
    return makeCard(rng);
  }
});
